name: CI

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.3.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1

      - name: Install node modules
        run: |
          yarn install
          node --version

      - name: Run tests
        run: yarn test
